### ISSUE TITLE
Smart contract deployment failed

### ISSUE THREAD

**Issue by omkarsunku** [Concordium/concordium-client#56]
**Bug Description**
When I try to execute Piggy_bank part 1 smart contract is failed to deploy.
I am using the following command to deploy a smart contract 

concordium-client module deploy piggy_bank_part1.wasm  --sender <account name>

Then it is asking for "Enter password for the credential with index 0 and signing key with index 0:" 
soon after I enter the password for index 0 it is showing the following message 
"concordium-client: user error (gRPC error: Transaction size exceeds maximum allowed size.)"

**Comment by abizjak** [comment]
These kinds of questions are generally better asked on the support forum https://support.concordium.software/ 

How did you compile your piggy-bank contract? It should fit comfortably inside the size limit if compiled with cargo-concordium. If you compiled it with cargo/rustc directly then you also need to strip it (e.g., using wasm-strip).

There is already an issue https://github.com/Concordium/concordium-client/issues/51 to make the user experience in the client better (it should warn you earlier than it does now).

I will close the issue here as duplicate. If you need support compiling smart contracts please ask at the linked support forum.
